spring.application.name=redis
spring.datasource.url=jdbc:mysql://localhost:3306/redis
spring.datasource.username=root
spring.datasource.password=""
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
jwt.private-key=ubSbY1tHL2hIsgShHZv3Qoz9ZLjhggHQynQLW3FZJD4SjDcNbcRtvhhM7tjR09Nx
jwt.acess-expiration=3600000  
jwt.refresh-expiration=86400000 
